### PR TITLE
feat: forbid default export backend

### PR DESCRIPTION
**Pull request by amaro0**

### CODE REVIEW

**Comment by Necromos** [comment]
Oh, why so? Is default some kind of a problem?

**Comment by amaro0** [comment]
https://basarat.gitbook.io/typescript/main-1/defaultisbad

**Comment by Necromos** [comment]
@masterborn/developers-backend any1 with their voice? :) My justification is that you should use 1 class per 1 file so generally, this shouldn't be a problem, the only case for it are types, tho just general rule of not using type file default may be good over here I suppose 🤔

**Comment by Kretolus** [comment]
Some good points, especially for discoverability/auto-complete and typos. Some of the others are less convincing.

Could be a good step for consistency as well, especially if we have cases of multiple exports. 👍

**Comment by Necromos** [comment]
@Kretolus can you give approve if you are OK with this change? thank you in advance!

**Review by Kretolus — DISMISSED** [review]

**Comment by Necromos** [comment]
Accepts here!

**Review by AdamKopf — DISMISSED** [review]

**Comment by amaro0** [comment]
Should this be merged?

**Comment by Necromos** [comment]
@amaro0 go for it I suppose :)

**Comment by amaro0** [comment]
Need one approve :)

**Review by Kretolus — APPROVED** [review]

**Pull request merged**
